### ISSUE TITLE
Support for multiple teams in core-structure.yaml

### ISSUE THREAD

**Issue by asharma3-ias** [Security-Phoenix-demo/autoconfig#22]
field `TeamName` in component/applicaiopn doesot allow multiple teams.

tested both :
```
TeamName: Team 1,Team 2 
```
and 
```
TeamName:
  - Team 1
  - Team 2 
```
it doesnt work

**Comment by franksec42** [comment]
implemented

**Comment by franksec42** [comment]
@asharma3-ias the field is called for the field is now called TeamNames instead of TeamName, and it's a list now.

**Comment by franksec42** [comment]
Examples:
:
Components:
\- ComponentName: product106-repo1 #name of the component
#Status: Production #Tag Optional
#Type: Release #Tag Optional
TeamNames: #names of the team as it appears in hives and teams
\- SP\_axelot20
\- SP\_lima20
