### ISSUE TITLE
Sync Application Updation

### ISSUE THREAD

**Issue by asharma3-ias** [Security-Phoenix-demo/autoconfig#24]
Python Script Not Updating Application on Subsequent Runs

I'm encountering an issue where my Python script isn't updating an application when it is run subsequent times.

Steps to Reproduce the Issue:

1. Create a new application using the 'core-structure.yaml' file and execute the Python script.
2. Subsequently,  make modifications to the application in 'core-structure.yaml', including adding a new repository.

Expected Outcome: Anticipate that any changes to the application made in the 'core-structure.yaml' file should prompt corresponding updates on the Phoenix backend upon rerunning the Python script.

Actual Outcome: Despite making changes and rerunning the script, no updates are performed on the Phoenix backend. The application remains unchanged.

**Comment by franksec42** [comment]
Fixed in latest PR
