### ISSUE TITLE
handle parameterising CISO email via yaml files

### ISSUE THREAD

**Issue by asharma3-ias** [Security-Phoenix-demo/autoconfig#3]
CISO Email is hardcoded to
https://github.com/Security-Phoenix-demo/autoconfig/blob/e79912e04ff0cb018ff66710844be2599a32f2a9/Python%20script/providers/Utils.py#L90

**Comment by franksec42** [comment]
this can be modified, for now this was an account as read only mode 

can be added in as one of the yaml parameter

**Comment by asharma3-ias** [comment]
Yes, as this user wont exists in customer env the API call will fail, Either this should be a mandator paramer in yaml or optional API call
