### ISSUE TITLE
Users in Hive adding hardcoded emails

### ISSUE THREAD

**Issue by asharma3-ias** [Security-Phoenix-demo/autoconfig#9]
When adding a lead to Hives.yaml using the current implementation, the system automatically appends @company.com to the provided input, regardless of whether a full email address or just a username is supplied. This behavior persists even when the input matches entries in the YAML Teams directory by either name or email, leading to incorrect or redundant email entries. This ends up adding a new non existent user

Steps to Reproduce:

- Attempt to add a lead to Hives.yaml by providing a name that exactly matches the entries in the YAML Teams directory.Alternatively, provide a complete email address, as listed in the YAML Teams directory, for the lead entry.

- Observe that the system modifies the input by appending @company.com, resulting in outputs like name@company.com or useremail@abc.com@company.com

https://github.com/Security-Phoenix-demo/autoconfig/blob/7c124dcb02ce0eca1362e5b2163f0af3d5208f2c/Python%20script/providers/YamlHelper.py#L109

**Comment by franksec42** [comment]
you can replace this with your company extension and just add names in the yaml

**Comment by asharma3-ias** [comment]
What's the best way to change @company.com ? do we need to change this line of code and is it the only change required ?  [YamlHelper.py#L180](https://github.com/Security-Phoenix-demo/autoconfig/blob/cb719c7d49b266d59744335f23a1d4796e89bbc9/Python%20script/providers/YamlHelper.py#L180).

Our goal is to achieve this without altering the code to facilitate easier updates to future versions of the project. Is there a way to make this change by using a parameter in the YAML configuration file instead? If so, could you please guide us on how to do this?

**Comment by franksec42** [comment]
this has been approved as FR
